### ISSUE TITLE
registreren nieuwe gebruiker

### ISSUE THREAD

**Issue by petersnoek** [dustdustinn/StudentPlatform#8]
als ik een veld niet goed invul (bijvoorbeeld een te kort wachtwoord: 12345)
dan krijg ik weliswaar een foutmelding, maar al mijn invoer is verdwenen.
dat vind ik erg gebruikersonvriendelijk.
Graag zorgen dat bij een invulfout mijn invoer bewaard wordt

**Comment by Romy96** [comment]
De issue is gefixt door gebruiken van set_values in normale inputs en set_select in select options.
